services:

  back_info-1:
    build: ./back_info
    environment:
      - INSTANCE_ID=back_info-1
    depends_on:
      psqlDB:
        condition: service_healthy
    networks:
     - microservices-net

  back_info-2:
    build: ./back_info
    environment:
      - INSTANCE_ID=back_info-2
    depends_on:
      psqlDB:
        condition: service_healthy
    networks:
     - microservices-net

  back_info-3:
    build: ./back_info
    environment:
      - INSTANCE_ID=back_info-3
    depends_on:
      psqlDB:
        condition: service_healthy
    networks:
     - microservices-net


  back_rockets-1:
    build: ./back_cohetes
    environment:
      - INSTANCE_ID=back_rockets-1
    depends_on:
      psqlDB:
        condition: service_healthy
    networks:
     - microservices-net

  back_rockets-2:
    build: ./back_cohetes
    environment:
      - INSTANCE_ID=back_rockets-2
    depends_on:
      psqlDB:
        condition: service_healthy
    networks:
     - microservices-net

  back_rockets-3:
    build: ./back_cohetes
    environment:
      - INSTANCE_ID=back_rockets-3
    depends_on:
      psqlDB:
        condition: service_healthy
    networks:
     - microservices-net

  back_satelites-1:
    build: ./back_satelites
    environment:
      - INSTANCE_ID=back_satelites-1
    depends_on:
      psqlDB:
        condition: service_healthy
    networks:
     - microservices-net


  back_satelites-2:
    build: ./back_satelites
    environment:
      - INSTANCE_ID=back_satelites-2
    depends_on:
      psqlDB:
        condition: service_healthy
    networks:
     - microservices-net


  back_satelites-3:
    build: ./back_satelites
    environment:
      - INSTANCE_ID=back_satelites-3
    depends_on:
      psqlDB:
        condition: service_healthy
    networks:
     - microservices-net


  gateway:
    build: ./gateway
    ports:
    - "8000:8000"
    depends_on:
      back_info-1:
        condition: service_started
      back_info-2:
        condition: service_started
      back_info-3:
        condition: service_started

      back_rockets-1:
        condition: service_started
      back_rockets-2:
        condition: service_started
      back_rockets-3:
        condition: service_started

      back_satelites-1:
        condition: service_started
      back_satelites-2:
        condition: service_started
      back_satelites-3:
        condition: service_started

      psqlDB:
        condition: service_healthy

    networks:
      - microservices-net
      
  psqlDB:
    image: postgres:18.6-alpine3.24
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "dyson_rings"
    volumes:
    - postgres_data:/var/lib/postgresql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - microservices-net

volumes:
  postgres_data:

networks:
  microservices-net:
    driver: bridge



