worker_processes auto;

events{
    worker_connections 100;
}

http{
    upstream info{
        server back_info-1:8080;
        server back_info-2:8080;
        server back_info-3:8080;
    }

    upstream satelites{
        server back_satelites-1:8080;
        server back_satelites-2:8080;
        server back_satelites-3:8080;
    }

    upstream rockets{
        server back_rockets-1:8080;
        server back_rockets-2:8080;
        server back_rockets-3:8080;
    }

    server{
        listen 8000;
        server_name nginx;
        

        location /satelite {
            proxy_pass http://satelites;
        }

        location /satelite/ {
            proxy_pass http://satelites;
        }

        location /rocket {
            proxy_pass http://rockets;
        }

        location /rocket/ {
            proxy_pass http://rockets;
        }

        location /tenant {
            proxy_pass http://info;
        }

        location /tenant/ {
            proxy_pass http://info;
        }

        location /take-off{
            proxy_pass http://info;
        }

        location /take-off/{
            proxy_pass http://info;
        }

        location /energy-transaction{
            proxy_pass http://info;
        }

        location /energy-transactions{
            proxy_pass http://info;
        }

        location /destination{
            proxy_pass http://info;
        }

        location /destination/{
            proxy_pass http://info;
        }


    }
}