
worker_processes auto;

events {
    worker_connections 100;
}

http {
    upstream info {
        server back_info-1:8000;
        server back_info-2:8000;
        server back_info-3:8000;
    }

    upstream satelites {
        server back_satelites-1:8000;
        server back_satelites-2:8000;
        server back_satelites-3:8000;
    }

    upstream rockets {
        server back_rockets-1:8000;
        server back_rockets-2:8000;
        server back_rockets-3:8000;
    }

    server {
        listen 8000;
        server_name nginx;

        # CORS para el frontend
        add_header Access-Control-Allow-Origin "http://localhost:5173" always;
        add_header Access-Control-Allow-Methods "GET, POST, PUT, PATCH, DELETE, OPTIONS" always;
        add_header Access-Control-Allow-Headers "Authorization, Content-Type, Accept, Origin, X-Requested-With" always;

        # Satélites
        location /satelite {
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_pass http://satelites;
        }

        location /hyper-satelite {
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_pass http://satelites;
        }

        # Rockets y hyper-rockets
        location /rocket {
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_pass http://rockets;
        }

        location /hyper-rocket {
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_pass http://rockets;
        }

        # Información
        location /tenant {
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_pass http://info;
        }

        location /take-off {
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_pass http://info;
        }

        location /energy-transaction {
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_pass http://info;
        }

        location /destination {
            if ($request_method = OPTIONS) {
                return 204;
            }

            proxy_pass http://info;
        }
    }
}
